spin_manifest_version = "1"
authors = ["Roman Volosatovs <rvolosatovs@riseup.net>"]
description = "devex evaluation"
name = "echo"
trigger = { type = "http", base = "/" }
version = "0.1.0"

[[component]]
id = "echo"
source = "target/wasm32-wasi/release/echo.wasm"
allowed_http_hosts = []
[component.trigger]
route = "/..."
[component.build]
command = "cargo build --target wasm32-wasi --release"
watch = ["src/**/*.rs", "Cargo.toml"]
